In [14]:
import numpy as np
import pandas as pd
df=pd.read_csv('glass.csv')
df.head()

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.0,0.0,1
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.0,0.0,1
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.0,0.0,1
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.0,0.0,1
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.0,0.0,1


In [15]:
x=df.drop(columns='Type')
x

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.00,0.0
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.00,0.0
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.00,0.0
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.00,0.0
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.00,0.0
...,...,...,...,...,...,...,...,...,...
209,1.51623,14.14,0.00,2.88,72.61,0.08,9.18,1.06,0.0
210,1.51685,14.92,0.00,1.99,73.06,0.00,8.40,1.59,0.0
211,1.52065,14.36,0.00,2.02,73.42,0.00,8.44,1.64,0.0
212,1.51651,14.38,0.00,1.94,73.61,0.00,8.48,1.57,0.0


In [16]:
y=df['Type']
y

0      1
1      1
2      1
3      1
4      1
      ..
209    7
210    7
211    7
212    7
213    7
Name: Type, Length: 214, dtype: int64

In [17]:
df.isna().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [19]:
x_train.ndim

2

In [20]:
y_test.ndim

1

In [21]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
scaler.transform(x_train)
scaler.transform(x_test)

array([[ 2.96144632e+00,  3.95808772e-01, -1.94335173e+00,
        -1.93943531e-01, -1.94002878e+00, -5.17922689e-01,
         3.60133611e+00, -3.53750449e-01,  4.42709887e-01],
       [-9.60374453e-01, -1.70671354e-01,  5.66239839e-01,
         2.54308287e-02,  7.76791661e-01, -1.98758751e-01,
        -7.04764852e-01, -3.53750449e-01, -5.69004426e-01],
       [-2.88598455e-01, -6.38633196e-01,  6.16575487e-01,
        -3.73431643e-01,  7.22725582e-01,  7.00108815e-02,
        -4.26181611e-01, -3.53750449e-01,  1.15090991e+00],
       [-4.34963058e-01, -4.66226202e-01,  5.51858226e-01,
         6.63610784e-01,  6.04161212e-02,  2.71588106e-01,
        -5.85372034e-01, -3.53750449e-01, -5.69004426e-01],
       [-9.52868576e-01, -8.11040191e-01,  5.44667419e-01,
         2.04918941e-01,  7.09209063e-01,  2.88386208e-01,
        -6.57007725e-01, -3.53750449e-01,  1.85910993e+00],
       [-2.28551438e-01, -4.90855772e-01,  6.02193873e-01,
        -4.93090385e-01,  4.38878670e-01,  2.547900

In [22]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)


KNeighborsClassifier()

In [23]:
y_pred=knn.predict(x_test)
y_pred

array([2, 2, 1, 2, 2, 1, 7, 7, 2, 1, 2, 5, 1, 5, 1, 2, 2, 2, 1, 1, 5, 5,
       2, 1, 2, 2, 1, 7, 1, 2, 2, 7, 1, 2, 2, 7, 2, 1, 3, 1, 2, 1, 1, 2,
       1, 1, 7, 1, 7, 2, 2, 2, 1, 1, 3, 7, 1, 1, 1, 2, 1, 3, 7, 7, 1],
      dtype=int64)

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_pred,y_test)
cm

array([[13,  6,  6,  0,  0,  0],
       [ 5, 16,  1,  0,  0,  1],
       [ 2,  1,  0,  0,  0,  0],
       [ 0,  1,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  2,  7]], dtype=int64)

In [29]:
a=accuracy_score(y_pred,y_test)
a

0.6