In [42]:
import numpy as np
import pandas as pd
df=pd.read_csv('diabetes.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1


In [43]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [44]:
x=df.drop(columns='Outcome')
x.ndim

2

In [45]:
y=df['Outcome']
y.ndim

1

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [47]:
x_train.shape


(537, 8)

In [48]:
x_test.shape

(231, 8)

In [49]:
y_train.shape

(537,)

In [50]:
y_test.shape

(231,)

# NORMALIZATION

# 1. Standerd Scaler
# 2. MinMax Scaler

In [51]:
#STD SCALER
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
# fit()---------> It collect or calculate the mean and standred deviation
scaler.fit(x_train)
# transform-----> It Impliments the calculations 
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)


In [52]:
#MINMAX SCALER
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
# fit()---------> It collect or calculate the mean and standred deviation
scaler.fit(x_train)
# transform-----> It Impliments the calculations 
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)


In [53]:
x_train

array([[1.        , 0.68686869, 0.57377049, ..., 0.55290611, 0.03030303,
        0.43137255],
       [0.        , 0.48989899, 0.52459016, ..., 0.54843517, 0.22950089,
        0.07843137],
       [0.06666667, 0.58585859, 0.57377049, ..., 0.40834575, 0.0530303 ,
        0.        ],
       ...,
       [0.86666667, 0.63636364, 0.73770492, ..., 0.64679583, 0.22192513,
        0.41176471],
       [0.26666667, 0.86363636, 0.59016393, ..., 0.64977645, 0.17557932,
        0.09803922],
       [0.6       , 0.51515152, 0.62295082, ..., 0.49031297, 0.25846702,
        0.49019608]])

In [54]:
x_test

array([[0.46666667, 0.68686869, 0.60655738, ..., 0.38748137, 0.25044563,
        0.58823529],
       [0.06666667, 0.76262626, 0.49180328, ..., 0.38897168, 0.04188948,
        0.01960784],
       [0.4       , 0.55050505, 0.49180328, ..., 0.37257824, 0.05392157,
        0.11764706],
       ...,
       [0.06666667, 0.45959596, 0.44262295, ..., 0.37555887, 0.06639929,
        0.03921569],
       [0.66666667, 0.84848485, 0.60655738, ..., 0.56631893, 0.20142602,
        0.25490196],
       [0.6       , 0.56565657, 0.67213115, ..., 0.50968703, 0.07798574,
        0.29411765]])

In [55]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
knn1=KNeighborsClassifier(n_neighbors=7)
base=GaussianNB()
sv=SVC()
lst=[knn1,base,sv]
from sklearn.metrics import confusion_matrix,accuracy_score

In [56]:
for i in lst:
    print('Model Name : ',i)
    i.fit(x_train,y_train)
    print('*'*100)
    y_pred1=i.predict(x_test)
    print(y_pred1)
    print('Accuracy Score : ',accuracy_score(y_test,y_pred1))
    print('*'*100)
    print('Confusion Matrix : ',confusion_matrix(y_test,y_pred1))

Model Name :  KNeighborsClassifier(n_neighbors=7)
****************************************************************************************************
[1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 1 0 0 1 0 1 0 1 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 1 0 0 0
 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1
 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 1 0 1 0 1 0 1 1 0 0 1 0 0 1 1 1 0 0
 0 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 0 0 1 0 1 0 0 0 0 1 0 1 0
 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 1 0]
Accuracy Score :  0.7748917748917749
****************************************************************************************************
Confusion Matrix :  [[128  18]
 [ 34  51]]
Model Name :  GaussianNB()
****************************************************************************************************
[0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0

# Model Creation


In [57]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)


,n_neighbors,7
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [58]:
y_pred=knn.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [59]:
print(knn.predict(scaler.transform([[1,89,66,23,94,28.1,0.167,21]])))

[1]


In [60]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
cm=confusion_matrix(y_pred,y_test)
cm

array([[128,  34],
       [ 18,  51]], dtype=int64)

In [61]:
a=accuracy_score(y_test,y_pred)
a


0.7748917748917749